//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rpgConsole {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rpgConsole.texts", typeof(texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výtej v aréně. Zde máš možnost bojovat proti nejlepším bojovníkům Reichu a vydobýt si tak slávu a bohatstvý.
        /// </summary>
        internal static string ArenaEntery {
            get {
                return ResourceManager.GetString("ArenaEntery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Důl  na růhy\n    p - pracovat v povrchovém dole. Za těch pár kamínků co najdeš nedostaneš skoro nic, ale zase ti nehrozí žádné nebezpečí\n    s - Těžba ve štole. Tady už můžeš získat solidní množství růhů. Nicméně bych si dával pozor, tady jsou úrazy na dením pořádku.\n    h - Tady v hlubiném dole najdeš jen ty nejčistčí růhy, ale riziko je veliké. V hlubiných tunelech se můžeš lehce strati a cesta ven taky není zrovna procházka růžovou zahradou. Dost možná se ti může stát že přijdeš třeba o nohu nebo o ru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string firstQuotaMine {
            get {
                return ResourceManager.GetString("firstQuotaMine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Důl na hůhy\n    p - povrchoví důl\n    s - štola\n    h - hlubiná těžba\n    z5 - návrat do města.
        /// </summary>
        internal static string helpQuotaMine {
            get {
                return ResourceManager.GetString("helpQuotaMine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les\n\n    lov - půjdeš na lov nestvůr\n    z5 - návrat.
        /// </summary>
        internal static string helpQuoteForest {
            get {
                return ResourceManager.GetString("helpQuoteForest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesto\nNápověda k ovládaní\n    help - zobrazí nápovědu\n    les - Vydáš se do lesa kde můžeš najít různá stvoření, která můžeš lovit\n    prehled - zobrazí informace o hráči\n    obchodnik - navtívíš místního obchodníka se zbraněmi a brnením\n    dul - zajdeš do místního dolu, kde si můžeš vydělat nějakou tu zlatku \n    konec - vrátíš se do menu.
        /// </summary>
        internal static string helpQuoteGame {
            get {
                return ResourceManager.GetString("helpQuoteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu\nNápověda k ovládaní\n   help - zobrazí nápovědu\n   zacit - započíst hru.
        /// </summary>
        internal static string helpQuoteMenu {
            get {
                return ResourceManager.GetString("helpQuoteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obchod\n    help - zobrazí tuto nápovědu\n    z - přejdeš na výběr zbraní\n    b - přejdeš na výběr brnění\n    z5 - vrátíš se zpět do města.
        /// </summary>
        internal static string helpQuoteShop {
            get {
                return ResourceManager.GetString("helpQuoteShop", resourceCulture);
            }
        }
    }
}
